'''
This script is used to get the clusters of the proxy matches. It reads the match files generated by the static validation script and counts how many times each known proxy package is matched.
The results are printed at the end, along with the number of files that had no matches and the number of files where nothing matched.
'''
import os

proxy_packages = {'okhttp3.internal', 'org.littleshoot', 'org.apache.http', 'io.netty.handler', 'com.purevpn.proxy', 'libv2ray', 'com.huawei.hms'}

clusters = {i: 0 for i in proxy_packages}

no_match_files = 0
nothing_matched = 0

def is_match_known(match_file):
    with open(match_file) as f:
        try:
            lines = f.readlines()
        except Exception as e:
            print(f"Error occured while processing file {match_file}: {e}")
            return False
                        
        for line in lines:
            line = line.strip()
            
            if line.startswith("Class: "):
            
                clazz1 = line.split(" ")[1].strip()
                clazz2 = line.split(" ")[3].strip()
                
                for proxy_package in proxy_packages:
                    if clazz1.lower().startswith(proxy_package) or clazz2.lower().startswith(proxy_package):
                        return proxy_package
                
    return False

for hash in os.listdir("outputs"):
    hash_folder = os.path.join("outputs", hash)
    match_files = os.listdir(hash_folder)
    
    if len(match_files) == 0:
        print(f"No matches found for {hash}")
        no_match_files += 1
        
    for match_file in match_files:
        given_match = is_match_known(os.path.join(hash_folder, match_file))
        if given_match:
            clusters[given_match] += 1
            print(f"Match found for {hash}: {given_match}")
            break
        
    else:
        print(f"No matching string for hash {hash}")
        nothing_matched += 1
            
print(clusters)
print(f"No. match files: {no_match_files}")
print(f"Nothing matched: {nothing_matched}")
